"""
convert_visco_inp.py -- Abaqus -> CalculiX deck converter for the
viscoelastic curing reference model.

Reads  : example-Job-Abaqus-Viscoelastic-Curing.inp   (Abaqus, part/assembly)
Writes : curing_visco_ccx.inp                          (flat CalculiX deck)

Adaptations performed:
  - part/assembly flattened (instance has identity transform)
  - C3D8T -> C3D8 (CalculiX handles coupled temp-disp with plain C3D8)
  - *Boundary, user (Abaqus DISP subroutine)  ->  *AMPLITUDE two-dwell
    MRCC cycle extracted from the DISP source:
       0 .. 2184 s   ramp 2.5 K/min to 389.15 K (116 C)
    2184 .. 5784 s   dwell 1
    5784 .. 7248 s   ramp 2.5 K/min to 450.15 K (177 C)
    7248 ..14448 s   dwell 2
   14448 ..18096 s   cool-down 2.5 K/min to 298.15 K
  - *Orientation rotation lines ("3, 90.") baked into the a/b vectors
    (the DLL UMAT builds the local frame from orab directly)
  - Material -> @VISCMOD (libviscmod.dll), 18 constants in the layout of
    Abaqus-Viscoelastic-Curing-Subroutine_calculix.for (Lee-Loos 3501-6
    kinetics + CTE/shrinkage); DEPVAR 64
  - HETVAL exotherm -> *DFLUX, BFNU (DLL dflux_ via ccx_ext.exe dispatch)
  - EL PRINT time histories on a through-thickness element column at the
    plate centre (x=y=0 corner of the quarter model)
"""
from pathlib import Path

SRC = Path(r"C:\YVAN\CODE\Curing\example-Job-Abaqus-Viscoelastic-Curing.inp")
DST = Path(r"C:\YVAN\CODE\Curing\curing_visco_ccx.inp")

lines = SRC.read_text(encoding="latin-1").splitlines()


def block(start_key, stop_at_star=True):
    i = next(k for k, l in enumerate(lines) if l.startswith(start_key))
    out = []
    j = i + 1
    while j < len(lines) and not lines[j].startswith("*"):
        out.append(lines[j])
        j += 1
    return i, out


_, node_lines = block("*Node")
_, elem_lines = block("*Element")


def read_nset(name):
    j = next(i for i, l in enumerate(lines)
             if l.startswith(f"*Nset, nset={name}, instance"))
    hdr = lines[j]
    ids = []
    k = j + 1
    if "generate" in hdr:
        a, b, c = [int(v) for v in lines[k].split(",")]
        return list(range(a, b + 1, c))
    while k < len(lines) and not lines[k].startswith("*"):
        ids += [int(v) for v in lines[k].split(",") if v.strip()]
        k += 1
    return ids


surf = read_nset("Set-2")   # exterior faces: temperature cycle
ntop = read_nset("Set-3")   # z = 25.4 mm face: uz = 0
nysym = read_nset("Set-4")  # y = 0 symmetry
nxsym = read_nset("Set-5")  # x = 0 symmetry

# ply element sets (from the part definition)
# _I1 = Ori-1 (rotation 90 deg about z -> fiber along y):
#       elements 1..2500 and 7501..10000
# _I2 = Ori-2 (0 deg -> fiber along x): elements 2501..7500
# through-thickness output column at the x=y=0 corner (plate centre),
# bottom -> top (determined from element centroids):
OUTCOL = [7500, 7475, 7450, 7425, 2401, 2426, 2451, 2476,
          10000, 9975, 9950, 9925, 2525, 2550, 2575, 2600]


def wlist(f, ids, per=12):
    for i in range(0, len(ids), per):
        f.write(" " + ", ".join(str(v) for v in ids[i:i + per]) + "\n")


with open(DST, "w", encoding="latin-1") as f:
    f.write("""** ================================================================
** curing_visco_ccx.inp -- CalculiX port of
** example-Job-Abaqus-Viscoelastic-Curing.inp (generated by
** convert_visco_inp.py -- edit that script, not this file)
**
** [0_4/90_8/0_4] AS4/3501-6 quarter plate 50.8x50.8x25.4 mm,
** 10 000 C3D8, two-dwell MRCC cycle on all exterior faces,
** viscoelastic (9-arm Prony + WLF) user material via libviscmod.dll,
** exotherm via DLL dflux_ (requires ccx_ext.exe).
** ================================================================
*NODE
""")
    for l in node_lines:
        f.write(l + "\n")
    f.write("*ELEMENT, TYPE=C3D8, ELSET=EALL\n")
    for l in elem_lines:
        f.write(l + "\n")

    f.write("*NSET, NSET=NALL, GENERATE\n 1, %d\n" % len(node_lines))
    f.write("*NSET, NSET=SURF\n"); wlist(f, surf)
    f.write("*NSET, NSET=NTOP\n"); wlist(f, ntop)
    f.write("*NSET, NSET=NYSYM\n"); wlist(f, nysym)
    f.write("*NSET, NSET=NXSYM\n"); wlist(f, nxsym)

    f.write("""*ELSET, ELSET=PLY90A, GENERATE
 1, 2500
*ELSET, ELSET=PLY0, GENERATE
 2501, 7500
*ELSET, ELSET=PLY90B, GENERATE
 7501, 10000
*ELSET, ELSET=PLY90
PLY90A, PLY90B
*ELSET, ELSET=OUTCOL
""")
    wlist(f, OUTCOL)

    f.write("""**
** Orientations. Rotation lines baked into a/b vectors:
** ORI0  : fiber along global x
** ORI90 : fiber along global y (90 deg about z)
*ORIENTATION, NAME=ORI0
 1., 0., 0., 0., 1., 0.
*ORIENTATION, NAME=ORI90
 0., 1., 0., -1., 0., 0.
**
** Material: viscoelastic curing composite via libviscmod.dll.
** Constants layout: see Abaqus-Viscoelastic-Curing-Subroutine_calculix.for
**  1-3  A1,A2,A3 kinetics pre-exponentials [1/min] (Lee-Loos 3501-6)
**  4-6  DE1,DE2,DE3 activation energies [J/mol]
**  7    B autocatalytic constant
**  8-10 Tg0, TgInf, DiBenedetto lambda
**  11   resin density [kg/m3], 12 total reaction enthalpy [J/kg]
**  13   fiber volume fraction
**  14-15 CTE fiber / transverse [1/K]
**  16-17 chem shrinkage fiber / transverse [-]
**  18   gel point alpha
*MATERIAL, NAME=@VISCMOD
*USER MATERIAL, CONSTANTS=18
 2.101e9, -2.014e9, 1.960e5, 8.07e4, 7.78e4, 5.66e4, 0.47, 253.15,
 493.15,  0.50,     1272.,   4.736e5, 0.52,  0.5e-6, 35.3e-6, -167.e-6,
 -8810.e-6, 0.30
*DEPVAR
 64
*CONDUCTIVITY, TYPE=ORTHO
 5.43, 0.4135, 0.4135
*SPECIFIC HEAT
 862.
*DENSITY
 1578.
**
*SOLID SECTION, ELSET=PLY0, ORIENTATION=ORI0, MATERIAL=@VISCMOD
*SOLID SECTION, ELSET=PLY90A, ORIENTATION=ORI90, MATERIAL=@VISCMOD
*SOLID SECTION, ELSET=PLY90B, ORIENTATION=ORI90, MATERIAL=@VISCMOD
**
*INITIAL CONDITIONS, TYPE=TEMPERATURE
NALL, 298.15
**
** Two-dwell MRCC cycle (from the Abaqus DISP user subroutine)
*AMPLITUDE, NAME=CURE_CYCLE, TIME=TOTAL TIME
      0.,  298.15,
   2184.,  389.15,
   5784.,  389.15,
   7248.,  450.15,
  14448.,  450.15,
  18096.,  298.15
**
*STEP, INC=100000
*COUPLED TEMPERATURE-DISPLACEMENT, DELTMX=50.
 100., 18096., 1.e-3, 200.
** raised iteration ceiling (vitrification stiffness jump, cf.
** curing_model2.inp)
*CONTROLS, PARAMETERS=TIME INCREMENTATION
4,8,9,40,30,4,,5,,
0.25,0.5,0.75,0.85,,,1.5,
** periodic restart file so an interrupted run can be resumed
*RESTART, WRITE, FREQUENCY=20
**
*BOUNDARY
NTOP, 3, 3, 0.
*BOUNDARY
NYSYM, 2, 2, 0.
*BOUNDARY
NXSYM, 1, 1, 0.
** autoclave air temperature on all exterior faces
*BOUNDARY, AMPLITUDE=CURE_CYCLE
SURF, 11, 11, 1.
** exotherm heat source through DLL dflux_ (HETVAL role)
*DFLUX
EALL, BFNU, 1.0
**
*NODE FILE, FREQUENCY=20
NT, U
*EL FILE, FREQUENCY=50
S
** through-thickness histories at the plate centre
*EL PRINT, ELSET=OUTCOL, FREQUENCY=2
S, SDV
*END STEP
""")

print("written", DST, "| nodes:", len(node_lines), "| elements:", len(elem_lines),
      "| surf:", len(surf), "| ntop:", len(ntop))
