"""
run_visco_warp.py -- warpage / spring-back variant of the viscoelastic
curing model.

Differences vs run_visco.py / convert_visco_inp.py:
  - ASYMMETRIC layup [0_8/90_8] (bottom half fiber along x, top half fiber
    along y), assigned by element-centroid z -- an unsymmetric cross-ply is
    the classic warpage driver (the original [0_4/90_8/0_4] is symmetric
    and would spring back to ~flat).
  - a second *STEP releases the cure constraints (top-face platen uz=0 and
    the prescribed surface temperature): only the two symmetry planes plus
    uz=0 at the plate-centre bottom node remain (isostatic), so the locked
    -in residual stresses re-equilibrate into free deformation = warpage.
  - no .frd field output (keeps files small); warpage is read from
    *NODE PRINT displacements of the bottom face in the .dat.

Usage:
  python run_visco_warp.py               # deck + (compile) + solve + plot
  python run_visco_warp.py --compile     # force recompiling libviscmod.dll
  python run_visco_warp.py --plot-only   # post-process an existing .dat
"""
import math
import re
import subprocess
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).parent
CCX = Path(r"C:\YVAN\CODE\CalculiX\src\ccx_ext.exe")
GFORTRAN = Path(r"C:\msys64\ucrt64\bin\gfortran.exe")
SRC = HERE / "example-Job-Abaqus-Viscoelastic-Curing.inp"
SRC_FOR = "Abaqus-Viscoelastic-Curing-Subroutine_calculix.for"
JOB = "curing_visco_warp"
THICK = 0.0254        # laminate thickness [m] (mesh is in meters)


# ---------------------------------------------------------------------------
# deck generation (adapted from convert_visco_inp.py)
# ---------------------------------------------------------------------------
def read_source():
    lines = SRC.read_text(encoding="latin-1").splitlines()

    def block(key):
        i = next(k for k, l in enumerate(lines) if l.startswith(key))
        out = []
        j = i + 1
        while j < len(lines) and not lines[j].startswith("*"):
            out.append(lines[j])
            j += 1
        return out

    def read_nset(name):
        j = next(i for i, l in enumerate(lines)
                 if l.startswith(f"*Nset, nset={name}, instance"))
        if "generate" in lines[j]:
            a, b, c = [int(v) for v in lines[j + 1].split(",")]
            return list(range(a, b + 1, c))
        ids, k = [], j + 1
        while k < len(lines) and not lines[k].startswith("*"):
            ids += [int(v) for v in lines[k].split(",") if v.strip()]
            k += 1
        return ids

    node_lines = block("*Node")
    elem_lines = block("*Element")
    coords = {}
    for l in node_lines:
        p = l.split(",")
        coords[int(p[0])] = (float(p[1]), float(p[2]), float(p[3]))
    conn = {}
    for l in elem_lines:
        p = [int(v) for v in l.split(",") if v.strip()]
        conn[p[0]] = p[1:]
    return (node_lines, elem_lines, coords, conn,
            read_nset("Set-2"), read_nset("Set-3"),
            read_nset("Set-4"), read_nset("Set-5"))


def wlist(f, ids, per=12):
    for i in range(0, len(ids), per):
        f.write(" " + ", ".join(str(v) for v in ids[i:i + per]) + "\n")


def gen_deck():
    node_lines, elem_lines, coords, conn, surf, ntop, nysym, nxsym = \
        read_source()

    # split elements bottom/top half by centroid z -> asymmetric [0_8/90_8]
    ebot, etop = [], []
    for eid, nds in conn.items():
        zc = sum(coords[n][2] for n in nds) / len(nds)
        (ebot if zc < THICK / 2 else etop).append(eid)
    ebot.sort(); etop.sort()

    # bottom-face node set (z ~ 0) for warpage output, + plate-centre node
    nbot = sorted(n for n, (x, y, z) in coords.items() if z < 1e-6)
    nctr = min(coords, key=lambda n: (coords[n][0] ** 2 + coords[n][1] ** 2
                                      + coords[n][2] ** 2))

    with open(HERE / f"{JOB}.inp", "w", encoding="latin-1") as f:
        f.write("""** ================================================================
** curing_visco_warp.inp -- ASYMMETRIC warpage variant (generated by
** run_visco_warp.py -- edit that script, not this file)
**
** [0_8/90_8] AS4/3501-6 quarter plate 50.8x50.8x25.4 mm, 10 000 C3D8.
** Step 1: two-dwell MRCC cure cycle, top face held flat (platen).
** Step 2: release (demold) -> spring-back / warpage.
** ================================================================
*NODE
""")
        for l in node_lines:
            f.write(l + "\n")
        f.write("*ELEMENT, TYPE=C3D8, ELSET=EALL\n")
        for l in elem_lines:
            f.write(l + "\n")

        f.write("*NSET, NSET=NALL, GENERATE\n 1, %d\n" % len(node_lines))
        f.write("*NSET, NSET=SURF\n"); wlist(f, surf)
        f.write("*NSET, NSET=NTOP\n"); wlist(f, ntop)
        f.write("*NSET, NSET=NYSYM\n"); wlist(f, nysym)
        f.write("*NSET, NSET=NXSYM\n"); wlist(f, nxsym)
        f.write("*NSET, NSET=NBOT\n"); wlist(f, nbot)
        f.write(f"*NSET, NSET=NCTR\n {nctr}\n")
        f.write("*ELSET, ELSET=EBOT\n"); wlist(f, ebot)
        f.write("*ELSET, ELSET=ETOP\n"); wlist(f, etop)

        f.write("""**
*ORIENTATION, NAME=ORI0
 1., 0., 0., 0., 1., 0.
*ORIENTATION, NAME=ORI90
 0., 1., 0., -1., 0., 0.
**
*MATERIAL, NAME=@VISCMOD
*USER MATERIAL, CONSTANTS=18
 2.101e9, -2.014e9, 1.960e5, 8.07e4, 7.78e4, 5.66e4, 0.47, 253.15,
 493.15,  0.50,     1272.,   4.736e5, 0.52,  0.5e-6, 35.3e-6, -167.e-6,
 -8810.e-6, 0.30
*DEPVAR
 64
*CONDUCTIVITY, TYPE=ORTHO
 5.43, 0.4135, 0.4135
*SPECIFIC HEAT
 862.
*DENSITY
 1578.
**
** asymmetric layup: bottom half 0 (fiber x), top half 90 (fiber y)
*SOLID SECTION, ELSET=EBOT, ORIENTATION=ORI0, MATERIAL=@VISCMOD
*SOLID SECTION, ELSET=ETOP, ORIENTATION=ORI90, MATERIAL=@VISCMOD
**
*INITIAL CONDITIONS, TYPE=TEMPERATURE
NALL, 298.15
**
*AMPLITUDE, NAME=CURE_CYCLE, TIME=TOTAL TIME
      0.,  298.15,
   2184.,  389.15,
   5784.,  389.15,
   7248.,  450.15,
  14448.,  450.15,
  18096.,  298.15
**
** ---------------- STEP 1: cure cycle (constrained) ----------------
*STEP, INC=100000
*COUPLED TEMPERATURE-DISPLACEMENT, DELTMX=50.
 100., 18096., 1.e-3, 200.
*CONTROLS, PARAMETERS=TIME INCREMENTATION
4,8,9,40,30,4,,5,,
0.25,0.5,0.75,0.85,,,1.5,
*RESTART, WRITE, FREQUENCY=50
*BOUNDARY
NTOP, 3, 3, 0.
*BOUNDARY
NYSYM, 2, 2, 0.
*BOUNDARY
NXSYM, 1, 1, 0.
*BOUNDARY, AMPLITUDE=CURE_CYCLE
SURF, 11, 11, 1.
*DFLUX
EALL, BFNU, 1.0
*NODE PRINT, NSET=NBOT, FREQUENCY=30
U
*EL PRINT, ELSET=EALL, FREQUENCY=1000000
S
*END STEP
**
** ---------------- STEP 2: release / demold -> warpage ----------------
*STEP, INC=1000
*COUPLED TEMPERATURE-DISPLACEMENT, DELTMX=50.
 5., 60., 1.e-3, 30.
*BOUNDARY, OP=NEW
NYSYM, 2, 2, 0.
*BOUNDARY
NXSYM, 1, 1, 0.
*BOUNDARY
NCTR, 3, 3, 0.
*BOUNDARY
NALL, 11, 11, 298.15
*NODE PRINT, NSET=NALL, FREQUENCY=5
U
*END STEP
""")
    print(f"[deck] {JOB}.inp written | ebot {len(ebot)} / etop {len(etop)} "
          f"elements | nbot {len(nbot)} nodes | centre node {nctr}")
    return coords


# ---------------------------------------------------------------------------
def build_dll():
    cmd = [str(GFORTRAN), "-shared", "-O2", "-ffixed-form",
           "-ffixed-line-length-none", "-Wl,--export-all-symbols",
           "-J", "_visco_build", "-I", "_visco_build",
           SRC_FOR, "umat_shim.f", "-o", "libviscmod.dll"]
    (HERE / "_visco_build").mkdir(exist_ok=True)
    print("[build]", " ".join(cmd))
    subprocess.run(cmd, cwd=HERE, check=True)


def run_ccx():
    print(f"[ccx] {CCX} -i {JOB}")
    r = subprocess.run([str(CCX), "-i", JOB], cwd=HERE)
    print("[ccx] exit", r.returncode)
    if r.returncode:
        sys.exit(r.returncode)


def parse_displacements():
    """-> {time: {node: (ux, uy, uz)}} from the NODE PRINT blocks."""
    hdr = re.compile(r"displacements .* time\s+([\d.E+\-]+)", re.I)
    out, cur = {}, None
    with open(HERE / f"{JOB}.dat", encoding="latin-1") as f:
        for raw in f:
            line = raw.strip()
            m = hdr.search(line)
            if m:
                cur = out.setdefault(float(m.group(1)), {})
                continue
            if cur is not None and line and line[0].isdigit():
                p = line.split()
                try:
                    cur[int(p[0])] = (float(p[1]), float(p[2]), float(p[3]))
                except (ValueError, IndexError):
                    cur = None
            elif cur is not None and line and re.match(r"[a-zA-Z]", line):
                cur = None
    return out


def make_plot(coords):
    disp = parse_displacements()
    times = sorted(disp)
    t_cure = max(t for t in times if t <= 18096.0)   # end of step 1
    t_rel = times[-1]                                 # end of release step
    print(f"[dat] displacement frames: {len(times)}, "
          f"cure end t={t_cure:.0f} s, release end t={t_rel:.0f} s")

    def field(t):
        # bottom-face (z=0) nodes only: step-2 frames contain all nodes
        d = disp[t]
        nodes = sorted(n for n in d if coords[n][2] < 1e-6)
        x = np.array([coords[n][0] for n in nodes])
        y = np.array([coords[n][1] for n in nodes])
        uz = np.array([d[n][2] for n in nodes])
        return x, y, uz

    x, y, uz_c = field(t_cure)
    _, _, uz_r = field(t_rel)

    # full-mesh text export: coordinates + displacements [mm], final frame
    d = disp[t_rel]
    txt = HERE / f"{JOB}_nodes_disp.txt"
    with open(txt, "w", encoding="utf-8") as f:
        f.write("# node    x[mm]        y[mm]        z[mm]        "
                "ux[mm]       uy[mm]       uz[mm]   (after release, "
                f"t={t_rel:.0f} s)\n")
        for n in sorted(d):
            cx, cy, cz = (v * 1e3 for v in coords[n])
            ux, uy, uz = (v * 1e3 for v in d[n])
            f.write(f"{n:6d} {cx:12.5f} {cy:12.5f} {cz:12.5f} "
                    f"{ux:12.6f} {uy:12.6f} {uz:12.6f}\n")
    print(f"[txt] {txt.name}: {len(d)} nodes exported")
    # warpage = bottom-face out-of-plane deviation, relative to plate
    # centre; mesh/displacements are in meters -> convert to mm
    ic = np.argmin(x ** 2 + y ** 2)
    wc = (uz_c - uz_c[ic]) * 1e3
    wr = (uz_r - uz_r[ic]) * 1e3
    xs, ys = x * 1e3, y * 1e3

    print(f"[warp] constrained (end of cure): min {wc.min():.4f} / "
          f"max {wc.max():.4f} mm")
    print(f"[warp] released   (spring-back) : min {wr.min():.4f} / "
          f"max {wr.max():.4f} mm  (peak-to-peak "
          f"{wr.max() - wr.min():.4f} mm over the quarter plate)")

    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig = plt.figure(figsize=(11, 8))
    ax1 = fig.add_subplot(2, 2, 1)
    ax2 = fig.add_subplot(2, 2, 2)
    vmax = max(abs(wr).max(), 1e-9)
    for ax, w, title in ((ax1, wc, "end of cure (platen on)"),
                         (ax2, wr, "after release (demold)")):
        tc = ax.tricontourf(xs, ys, w, levels=21, cmap="RdBu_r",
                            vmin=-vmax, vmax=vmax)
        ax.set_aspect("equal")
        ax.set_title(f"bottom-face uz [mm], {title}", fontsize=10)
        ax.set_xlabel("x [mm] (0 = plate centre)")
        ax.set_ylabel("y [mm]")
        fig.colorbar(tc, ax=ax, shrink=0.85)

    # profiles along x-edge (y=0), y-edge (x=0) and diagonal
    ax3 = fig.add_subplot(2, 1, 2)
    for sel, lab, st in ((ys < 1e-3, "along x (y=0)", "-"),
                         (xs < 1e-3, "along y (x=0)", "--")):
        r = np.where(sel, np.hypot(xs, ys), np.nan)
        o = np.argsort(r[sel])
        ax3.plot(np.hypot(xs, ys)[sel][o], wr[sel][o], "b" + st, lw=1.8,
                 label=f"released, {lab}")
        ax3.plot(np.hypot(xs, ys)[sel][o], wc[sel][o], "0.6" + st, lw=1.2,
                 label=f"constrained, {lab}")
    ax3.set_xlabel("distance from plate centre [mm]")
    ax3.set_ylabel("uz - uz(centre) [mm]")
    ax3.grid(True, alpha=0.3)
    ax3.legend(fontsize=9)
    ax3.set_title("warpage profiles, bottom face", fontsize=10)

    fig.suptitle("Asymmetric [0_8/90_8] laminate -- residual-stress "
                 "spring-back after demold (viscoelastic model)",
                 fontsize=12, fontweight="bold")
    fig.tight_layout()
    out = HERE / "curing_visco_warpage.png"
    fig.savefig(out, dpi=110)
    print("[plot] saved", out)


def main():
    coords = None
    if "--plot-only" not in sys.argv:
        coords = gen_deck()
        dll = HERE / "libviscmod.dll"
        if "--compile" in sys.argv or not dll.exists():
            build_dll()
        else:
            print(f"[build] reusing existing {dll.name} "
                  "(pass --compile to force a rebuild)")
        run_ccx()
    if coords is None:
        coords = read_source()[2]
    make_plot(coords)


if __name__ == "__main__":
    main()
